# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"

jobs:
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          install-command: yarn --frozen-lockfile --silent
          working-directory: client
      - name: Run Linting
        run:  npm run lint
        working-directory: client

  backend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          install-command: yarn --frozen-lockfile --silent
          working-directory: server
      - name: Run Linting
        run:  npm run lint
        working-directory: server

