site_name: IndEAA Documentation
copyright: Copyright System Health Lab
repo_url: https://github.com/uwasystemhealth/IndEAA
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: brown
    scheme: default # "slate" is dark, "default" is white
  logo: images/shl.png
  favicon: images/shl.png
  features:
    - navigation.tabs
plugins:
  - search
  - with-pdf:
        author: Frinze Erin Lapuz and Michael Nefiodovas
        copyright: System Health Lab
        cover_title: IndEAA
        cover_subtitle: Streamlining course review processs
        cover_logo: ./docs/images/shl.png
        enabled_if_env: ENABLE_PDF_EXPORT
  # at the moment pdf cannot render relative linked image https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/issues/92
  - mermaid2:
      version: 8.8.2
      arguments:
        theme: white # white | dark

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tabbed
  - footnotes
  - pymdownx.critic
  - attr_list
  - def_list
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 4
  - codehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_javascript:
  - https://unpkg.com/mermaid@8.8.2/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Overview: index.md
- Coordinator:
  - Introduction: coordinator/index.md
- Reviewer:
  - Introduction: reviewer/index.md
- Administrator:
  - Introduction: administrator/index.md
- Developer:
  - Introduction: developer/index.md
  - Coding Standards: developer/coding_standards.md
  - Data Engineering: developer/data_engineering.md
  - Database Support Scripts: developer/database_support_scripts.md
  - Frontend:
    - Component vs Page: developer/frontend/component_vs_page.md
    - Transport/Integration Layer (Feathers-redux): developer/frontend/feathers_redux.md
    - Notifications with Redux Saga: developer/frontend/notifications.md
  - Backend:
    - Permission: developer/backend/permission.md
    - Services: developer/backend/services.md
- Changelog: changelog.md
